### ISSUE TITLE
hrmtool: add support for S625sx srd-files

### ISSUE THREAD

**Issue by krissen** [ra1fh/s725#1]
Hi,

I have a bunch of old `srd`-files, recorded by a Polar s625sx -watch. I've been trying to convert them to a filetype which would be more generally supported (like `tcx`), but so far I haven't managed it.

I found your `hrmtool`, which looks to be able to do precisely what I'm looking for, but it chokes on my `srd`-files:
```
❯ hrmtool -i srd -o tcx -f 20050211T123700.02625.srd -F test.tcx -v
workout_read_buf: unable to auto-detect HRM type
fatal: 20050211T123700.02625.srd: invalid file
```

I have uploaded a `srd` [here](https://www.dropbox.com/s/esdb8nskldo2z3t/20050211T123700.02625.srd?dl=0).

I suspect this is an old project of yours, maybe not relevant anymore, but nevertheless hoping it would be an easy fix to add support for s625 srd-files.

Kind regards,
Kristian

**Comment by krissen** [comment]
I might add that `s725plot` chokes in the following manner:
```
s725plot 20050211T123700.02625.srd test/
Traceback (most recent call last):
  File "/Users/krisniem/dev/s725/s725plot", line 339, in <module>
    meta = read_meta(filename)
  File "/Users/krisniem/dev/s725/s725plot", line 59, in read_meta
    data = file.read()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa5 in position 19: invalid start byte
```

I remember using the program `s710` back in the day, of which I believe `s725` is a fork? The author of `s710` helped me sort it out at the time --- more than 15 years ago. There was some minor changes needed in the code. Alas, I don't remember how; the old code with my changes isn't stored; and I can't access the discussion I had with Dave, as it took place on his forums ---  ( http://daveb.net/forum/viewtopic.php?p=454#454 ) --- which is not available anymore. (No; the Wayback machine hasn't got it stored either.)

**Comment by krissen** [comment]
Oh, it's actually really close to working as-is!

Looked at the code a bit and testing this and that, I forced workout detection to return `S725_HRM_S625X` in `workout.c` (line 186) and _`srd` to `tcx` conversion actually worked!_ 

In other words, `hrmtool` currently fails to detect that there indeed is valid HRM-data, but once autodetection is disabled, it reads _most_ stuff successfully from the `srd`-file!

So far the only piece missing seems to be `DistanceMeters` in `TrackPoint` data:
```
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<TrainingCenterDatabase
    xmlns="http://www.garmin.com/xmlschemas/TrainingCenterDatabase/v2"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.garmin.com/xmlschemas/TrainingCenterDatabase/v2
    http://www.garmin.com/xmlschemas/TrainingCenterDatabasev2.xsd">
<Activities>
  <Activity Sport="Running">
    <Id>2005-02-11T12:37:00Z</Id>
    <Lap StartTime="2005-02-11T12:37:00Z">
      <TotalTimeSeconds>3097.00000</TotalTimeSeconds>
      <DistanceMeters>9400.00000</DistanceMeters>
      <MaximumSpeed>302.00000</MaximumSpeed>
      <Calories>9463</Calories>
      <AverageHeartRateBpm><Value>60</Value></AverageHeartRateBpm>
      <MaximumHeartRateBpm><Value>60</Value></MaximumHeartRateBpm>
      <Intensity>Active</Intensity>
      <TriggerMethod>Manual</TriggerMethod>
      <Track>
        <Trackpoint>
        <!-- sample #0 -->
          <Time>2005-02-11T12:37:00Z</Time>
          <AltitudeMeters>20.000000</AltitudeMeters>
          <DistanceMeters>0.000000</DistanceMeters>
          <HeartRateBpm><Value>100</Value></HeartRateBpm>
        </Trackpoint>
        <Trackpoint>
        <!-- sample #1 -->
          <Time>2005-02-11T12:37:00Z</Time>
          <AltitudeMeters>20.000000</AltitudeMeters>
          <DistanceMeters>0.000000</DistanceMeters>
          <HeartRateBpm><Value>109</Value></HeartRateBpm>
        </Trackpoint>
        <Trackpoint>
        <!-- sample #2 -->
          <Time>2005-02-11T12:37:00Z</Time>
          <AltitudeMeters>20.000000</AltitudeMeters>
          <DistanceMeters>0.000000</DistanceMeters>
          <HeartRateBpm><Value>111</Value></HeartRateBpm>
        </Trackpoint>
        <Trackpoint>
```

Total distance is correct; as is start time, date, total time, calories, heart rate etc. But all sample data for `DistanceMeters` is 0. Also, `MaximumSpeed` seems a bit optimistic. 😂

**Comment by krissen** [comment]
I had the "patched" `hrmtool` convert all of my ca. 250 `srd`-files. All seemed to have been successfully converted. Out of them, 12 also had distance-data for individual `TrackPoint`; the rest +200 all had zeroes in `TrackPoint` -> `DistanceMeters`. All had valid total distance though.

The previously [provided](https://www.dropbox.com/s/esdb8nskldo2z3t/20050211T123700.02625.srd?dl=0) `srd` is an example of the "majority type", i.e. files with nothing but 0.000000 `DistanceMeters` in `TrackPoint` data. [This](https://www.dropbox.com/s/q6474pzo7k9fb1l/20060814T171741.02984.srd?dl=0) is a `srd` -file which resulted in a `tcx` _with_ valid `DistanceMeters` in `TrackPoint`. I do not know why there is a difference. Both are of activity type `Running`.

**Comment by ra1fh** [comment]
> ```
> ❯ hrmtool -i srd -o tcx -f 20050211T123700.02625.srd -F test.tcx -v
> workout_read_buf: unable to auto-detect HRM type
> fatal: 20050211T123700.02625.srd: invalid file
> ```
> 
> I have uploaded a `srd` [here](https://www.dropbox.com/s/esdb8nskldo2z3t/20050211T123700.02625.srd?dl=0).
> 
> I suspect this is an old project of yours, maybe not relevant anymore, but nevertheless hoping it would be an easy fix to add support for s625 srd-files.

I still have S725 watches, but I don't use them much anymore. I haven't intentionally removed S625 compatibility after forking from s710, but I don't have such a watch to test with. I'll take a look at the sample files

**Comment by ra1fh** [comment]
> I might add that `s725plot` chokes in the following manner:
> 
> ```
> s725plot 20050211T123700.02625.srd test/
> ...
> UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa5 in position 19: invalid start byte
> ```

s725plot needs txt format input as generated by hrmtool or s725get. It can't parse the binary srd file format.

**Comment by ra1fh** [comment]
@krissen I've just pushed a change to allow forcing the srd variant with hrmtool -I. With that I get somewhat plausible data from your sample files as well.

However, the recording interval is zero, which is visible in the timestamps of your tcx sample output above and more prominent in the txt output as it caused a division by zero (fixed as well). No idea what's wrong there.

**Comment by krissen** [comment]
Thank you for looking into it; much appreciated.

Can confirm plausible data with the new `-I S625` switch. (And data, although _implausible_ if I try `-I S725` with the same `srd`.)

Hmm. When I last dabbled with these things, I made a rudimentary "webapp" (PHP) which parsed srd files (last update was in 2004 😂). [This](https://sourceforge.net/p/polaring/svn/HEAD/tree/polaring/trunk/functions/srdParser.php) is the code that parsed `srd` -files. Due to recent updates to Apache/PHP, it currently doesn't work, so I can't confirm, but I'm pretty sure I got reasonable timestamp-data. 

There's a check for type of monitor in lines 215-223, pretty much identical to what is used in `hrmtool`. However, the webapp only differentiates between (I believe) s710 and "other", where I used "other" --- so "monitor 12" in the parlance of the webapp (e.g. `-I S625`).

There are a couple of times when type of monitor makes a difference in the parser. One that is relevant to sample data, is on lines 531-535, which sets a different index for lap start used in calculation of both lap and sample data. 78 for "monitor 11" and 109 for "monitor 12". The number is used a couple of times in the lines thereafter, some of which should be relevant for timestamp --- at least for lap, not sure about sample.

I'll see if I can figure out how to translate what I did then, to hrmtool.

... By the by, at least on macOS I have to add `#include <sys/types.h>` to `xmalloc.c` for the project to build successfully.

------ EDIT 

Ah yes, srdparser's `indexLapStart` is `S725_HEADER_SIZE_S625X` / `_S725` / `_S610` in `workout_int.h`. However, that seems to mean I must've remembered wrong regarding the aforementioned "monitor 11" and 12, as the header size for s625 in `hrmtool` corresponds to the index offset for monitor 11 in srdparser. 

(Indeed, by now I'm not sure if this is in any way helpful input, or just meaningless chatter.)

**Comment by krissen** [comment]
Rambling on in the hopes that it might make sense to some extent.

Sample timestamp seems to be calculated.

(1) In srdparser, lines [317](https://sourceforge.net/p/polaring/svn/HEAD/tree/polaring/trunk/functions/srdParser.php#l317)-330, sample interval is fetched. 

(2) That is used, in `calculateTimeSamples` (parserFunctions.php, lines [136](https://sourceforge.net/p/polaring/svn/HEAD/tree/polaring/trunk/functions/parserFunctions.php#l136)-147). (Distance is calculated in lines [108](https://sourceforge.net/p/polaring/svn/HEAD/tree/polaring/trunk/functions/parserFunctions.php#l108)-118.)

**Comment by ra1fh** [comment]
In your sample files the recording interval is 0x10. The code only expects 0, 1 or 2. I've pushed a change to ignore the higher bits. That works out for those files, number_of_samples * recording_interval matches the exercise duration with the resulting interval of 5 seconds.

**Comment by krissen** [comment]
Getting really close now! 

Again; thank you for taking time to help me. Hopefully others will benefit as well --- I found no other (working) way of reading `srd`-files, not even by Polar themselves...

When looking at my 2005-sample-srd, I have the following in the summary:
```
<Lap StartTime="2005-02-11T12:37:00Z">
      <TotalTimeSeconds>3097.00000</TotalTimeSeconds>
      <DistanceMeters>9400.00000</DistanceMeters>
      <MaximumSpeed>302.00000</MaximumSpeed>
        ...
```

And in the last sample I have the following:
```
        ...
        <!-- sample #619 -->
          <Time>2005-02-11T13:28:35Z</Time>
          <AltitudeMeters>11.000000</AltitudeMeters>
          <DistanceMeters>9.380295</DistanceMeters>
          <HeartRateBpm><Value>166</Value></HeartRateBpm>
        </Trackpoint>
      </Track>
    </Lap>
  </Activity>
```

`DistanceMeters` in the summary is 9400 meters, which is plausible, but the last entry on the odometer says 9.380295. So just a decimal error (or unit error; km -vs- m); _sample_ `DistanceMeters` should be `n * 1000` for it to be _meters_.

Is speed calculated or read from the file? If calculated, perhaps this will fix that as well?

Not sure if it, perhaps, could be due to units not having been autodetected correctly? 🤔

**Comment by ra1fh** [comment]
> sample DistanceMeters should be n * 1000 for it to be meters.

Yes, the track point distances in the TCX are wrong by a factor of 1000. I've pushed a change to master to correct that. Thanks for the report!

> Is speed calculated or read from the file?

Total distance and lap distances are part of the SRD with a granularity of 100m. Also the speed values per track point are part of the SRD. The distance per track point is then calculated from the speed. So a small difference between the distance totals and the track points is to be expected as long as the difference is less than 100m.

**Comment by krissen** [comment]
Excellent. Thank you again! 🙏 Successfully converted all `srd`-files, and data seems ok.
